<<<<<<< HEAD
import type { Metadata } from "next";
=======
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
>>>>>>> d575cf813cfc72b32ce023e91ae2753634931571
import "./globals.css";
import {color} from "@/lib/constants/colors";

<<<<<<< HEAD
=======
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
>>>>>>> d575cf813cfc72b32ce023e91ae2753634931571

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="icon" content="#" />
      </head>
      <body
<<<<<<< HEAD
        className={`antialiased h-[100vh] h-[100%]  flex flex-col justify-center items-center`}
=======
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>>>>>>> d575cf813cfc72b32ce023e91ae2753634931571
      >
        {children}
      </body>
    </html>
  );
}
